---
- name: Run some tasks
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: ssh
    ansible_shell_type: cmd
  tasks:
    - name: Create Folder
      ansible.windows.win_file:
        path: 'C:\{{ foo_role }}'
        state: directory
...
