---
- name: Run some tasks
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: ssh
  tasks:
    - name: Create Folder
      ansible.windows.win_file:
        path: 'C:\miq'
        state: directory
...
